DELETE CURRENCY_NAME_INFO;
INSERT INTO CURRENCY_NAME_INFO ( CURRENCY_ID,CURRENCY_NAME ) VALUES ('USD','美元');
INSERT INTO CURRENCY_NAME_INFO ( CURRENCY_ID,CURRENCY_NAME ) VALUES ('GBP','英磅');
INSERT INTO CURRENCY_NAME_INFO ( CURRENCY_ID,CURRENCY_NAME ) VALUES ('EUR','歐元');